apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: admin-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/appdev/module1/username"
        objectType: "ssmparameter"
      - objectName: "/appdev/module1/password"
        objectType: "ssmparameter"