apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterpolicyreport
  namespace: default
subjects:
- kind: ServiceAccount
  name: eks-svc-account # Name of the ServiceAccount
  namespace: default
roleRef:
  kind: ClusterRole # This must be Role or ClusterRole
  name: clusterpolicyreport # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io