name: "Runner-Windows"
gitlabUrl: https://gitlab.com/
log-level: info
tags: "arm64"
runnerRegistrationToken: GR1348941RKqfnSdxdp9gRqHsdpz6
runUntagged: false
clusterWideAccess: true
serviceAccountName: default
rbac:
  create: true
  rules:
    - resources: ["pods", "secrets"]
      verbs: ["get", "list", "watch", "create", "patch", "delete"]
    - apiGroups: [""]
      resources: ["pods/exec", "configmaps", "pods/attach", "secrets"]
      verbs: ["create", "patch", "delete", "update"]
nodeSelector:
  kubernetes.io/os: "linux"
runners:
  config: |
    [[runners]]
      executor = "kubernetes"
      [runners.kubernetes]
        tags = "arm64"
        image =  "arm64v8/alpine"
        namespace = "default"
        poll_timeout = 3600
        [runners.kubernetes.node_selector]
          "kubernetes.io/arch" = "arm64"
          "kubernetes.io/os" = "linux"
  nodeSelector:
    kubernetes.io/os: "linux"
    kubernetes.io/arch: "arm64"